### ISSUE TITLE
return scores in objectproposal

### ISSUE THREAD

**Issue by jhung0** [broadinstitute/keras-rcnn#32]
Instead of returning just proposals, return scores as well https://github.com/broadinstitute/keras-rcnn/blob/master/keras_rcnn/backend/tensorflow_backend.py#L86

**Comment by JihongJu** [comment]
What do we need the score for? Isn't the ROIs enough?

**Comment by jhung0** [comment]
We don't use it, but it's possible they could be useful

**Comment by JihongJu** [comment]
I'd say it is definitely very helpful to rank the object proposals by the score. And I can also imagine something like filtering the proposals by ranking or by thresholding. But I am not sure we should go for returning proposals with scores since the scores will be thrown away in the ROI layer anyway.
