### ISSUE TITLE
Intersection over Union (IoU) algorithm

### ISSUE THREAD

**Issue by yanfengliu** [broadinstitute/keras-rcnn#47]
I think `IoU` is supposed to be like this: 
![iou_equation](https://user-images.githubusercontent.com/11828748/28532441-64d0137c-705f-11e7-8c0a-4bd6e31600e4.png)

But based on the code in this library, the definition of `union` is currently implemented as the rectangle defined by the top left corner of the first box and the bottom right corner of the second box, which is bigger than the true union. 

[code related to this issue here](https://github.com/broadinstitute/keras-rcnn/blob/78313b6e9adf918b92ee1842adc199cb8fbe8df0/keras_rcnn/preprocessing/_object_detection.py#L19-L24)

**Comment by hgaiser** [comment]
Nice catch, looks like you're correct. Interestingly in https://github.com/broadinstitute/keras-rcnn/blob/master/keras_rcnn/backend/tensorflow_backend.py#L138-L151 it seems to be properly implemented using tensorflow functions. Will you make a PR to fix this?

**Comment by yanfengliu** [comment]
@hgaiser Yeah I can do that

**Comment by jhung0** [comment]
Thanks for catching that!

On Jul 24, 2017 8:41 AM, "Yanfeng Liu" <notifications@github.com> wrote:

@hgaiser <https://github.com/hgaiser> Yeah I can do that

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/broadinstitute/keras-rcnn/issues/47#issuecomment-317516340>,
or mute the thread
